packages:
  - apps/*
  - packages/*

injectWorkspacePackages: true

overrides:
  '@tarojs/components@4.2.1>swiper': 12.1.2

allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  '@swc/core': true
  '@tarojs/binding': true
  '@tarojs/cli': true
  core-js: false
  core-js-pure: false
  cpu-features: false
  esbuild: true
  protobufjs: false
  ssh2: false
  unrs-resolver: true
