import type { ServerConfig } from './config.js';

export const TEST_CONFIG: ServerConfig = {
  nodeEnv: 'test',
  host: '127.0.0.1',
  port: 3000,
  logLevel: 'silent',
  databaseUrl: 'postgres://test.invalid/avalon',
  redisUrl: 'redis://test.invalid:6379',
  rateLimitMax: 100,
  rateLimitHmacSecret: 'm0-test-rate-limit-key-material-0001',
  joinRateLimitMax: 5,
  sessionTokenPepper: 'm2-test-session-token-pepper-material-0001',
  idempotencyEncryptionSecret: 'm2-test-idempotency-encryption-material-0001',
  sessionTtlSeconds: 1_800,
  wechatAppId: 'wx0240d55d0f3e4811',
  wechatAppSecret: 'm8-test-wechat-app-secret-material',
  wechatIdentityPepper: 'm8-test-wechat-identity-pepper-material-0001',
  wechatAuthEnforcement: 'required',
  realtimePublicUrl: 'wss://localhost.invalid/game-v2',
  trustedProxyCidrs: [],
  handshakeIpRateLimit: 30,
  pendingAuthLimit: 100,
  authTimeoutMs: 3_000,
  instanceConnectionLimit: 6_000,
  globalConnectionLimit: 12_000,
  sessionSocketLimit: 2,
  terminalAckRateLimit: 3,
  audioTelemetryRateLimit: 6,
  createJoinIpRateLimit: 30,
  createJoinGlobalRateLimit: 600,
  databasePoolMax: 10,
  databaseQueryTimeoutMs: 2_000,
  outboxBatchSize: 25,
};
